projects:
  resumeparser:
    schemaPath: amplify/backend/api/resumeparser/build/schema.graphql
    includes:
      - api
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
